sudo: required
services:
  - docker

before_install:
  - docker build -t taruncx101/docker-react -f Dockerfile.dev .

script:
  #- docker run taruncx101/docker-react npm run test -- --coverage
  - docker run -e CI=true taruncx101/docker-react npm run test